site_name: SURVEYHAWK DOCS
repo_url: https://git.i.mercedes-benz.com/LOBERNH/surveyhawk_docs
theme:
   name: material
   logo: assets/grau_sh_logo.png
   icon:
     repo: fontawesome/brands/github
   palette: 
     scheme: default
     primary: black
     accent: black
   features:
     - navigation.instant
     - navigation.tabs
     - navigation.tracking
     - navigation.path
     - navigation.indexes
     - navigation.expand
     - search.highlight
     - search.suggest
     - content.code.copy
nav:
  - Home: index.md
  - Repository Health: Repository-Health/Repository-Health.md
  - Guide:
      - Installation: Guide/Installation.md
      - Getting Started: Guide/Getting-Started.md
      - Features: Guide/Features.md
  - Example: Example/Example.md
  - Results: Results/Results.md
  - Contributing: Contributing/Contributing.md
  - FAQ: FAQ/FAQ.md
extra:
  generator: true
plugins:
  - search
  - awesome-pages
  - macros
markdown_extensions: 
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
####
# navigation definition and ordering by awesome-pages plugin.
# definition is done in all .pages files. 
####
#nav:
